### ISSUE TITLE
Which Marlin git commit is this based on?

### ISSUE THREAD

**Issue by hellerbarde** [Velleman/Vertex-Nano-Firmware#1]
Could you maybe tell me what commit from the official Marlin repository this is based on?

So I can more easily find what exactly was changed.

Thank you very much for your very quick response in releasing this source 👍 👍

**Comment by velbn** [comment]
Hi 

This is based on RC7. We downloaded the version. We didn't clone.
So we can't tell exactly which version(commit)

**Comment by hellerbarde** [comment]
Thank you. 

My experiments suggest that it's commit d97dc102. It's the commit where the diff is shortest ;)
